# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'
overrides = YAML.load_file 'vagrant.yml'
BOX_NAME = overrides['box_name']
HOST_NAME = overrides['host_name']
ISO_MOUNT = overrides['iso_mount']
V_CONSOLE = overrides['v_console']
V_CPU = overrides['v_cpu']
V_MEMORY = overrides['v_memory']

Vagrant.require_version ">= 1.8.0"
VAGRANTFILE_API_VERSION = "2"

# base box NOT exposed since changing may cause unforseen problems
BASE_BOX = "boxcutter/centos67"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = BASE_BOX
  config.vm.hostname = HOST_NAME

  config.vm.network "forwarded_port", guest: 80, host: 8000, id: "http", auto_correct: true
  config.vm.network "forwarded_port", guest: 3306, host: 8306, id: "mysql", auto_correct: true

  # customize VirtualBox defaults
  config.vm.provider "virtualbox" do |vb|
    # assign v-cpus
    vb.cpus = V_CPU

    # true means display hypervisor console window, false means don't display
    vb.gui = V_CONSOLE

    # guest OS memory allocation (MB)
    vb.memory = V_MEMORY

    # rename the box to a friendly name
    if BOX_NAME != 'default'
      vb.name = BOX_NAME
    end

    # increase video ram to avoid warning on default (8 MB)
    vb.customize ["modifyvm", :id, "--vram", "9"]
  end


  # bootstrap EPEL-6 and Ansible (also requires bootstrapping addtn'l python libraries)
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum -y --nogpgcheck localinstall /vagrant/deploy/epel-release-6-8.noarch.rpm
    sudo rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
    sudo yum -y upgrade ca-certificates --disablerepo=epel
    sudo yum -y install openssl-devel
    sudo yum -y install python-devel
    sudo yum -y install python-pip
    sudo yum -y --nogpgcheck localinstall /vagrant/deploy/ansible-2.0.1.0-2.el6.noarch.rpm
    sudo yum -y --nogpgcheck localinstall /vagrant/deploy/remi-release-6.rpm
    sudo yum -y install yum-utils
    sudo yum-config-manager --enable remi-php55
  SHELL


  # Patch for https://github.com/mitchellh/vagrant/issues/6793
  config.vm.provision "shell" do |s|
    s.inline = '[[ ! -f $1 ]] || grep -F -q "$2" $1 || sed -i "/__main__/a \\    $2" $1'
    s.args = ['/usr/bin/ansible-galaxy', "if sys.argv == ['/usr/bin/ansible-galaxy', '--help']: sys.argv.insert(1, 'info')"]
  end 


  # upload custom Ansible config to enable logging and task profiling
  config.vm.provider "virtualbox" do |vb|
    config.vm.provision "file", source: "deploy/ansible.cfg", destination: "~/.ansible.cfg"
  end 


  # provision the box with Ansible
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "/vagrant/provisioning/ansible/playbook.yml"

    # extra_vars causes 'ERROR: Expecting property name: line 1 column 1 (char 1)'
    # command line becomes --extra-vars={"catalina_base":"/srv/ues"} 
    # command line should be --extra-vars='{"catalina_base":"/srv/ues"}' (with single quotes)
    #ansible.extra_vars = {
    #  catalina_base: CATALINA_BASE
    #}

    #ansible.verbose = "vvv"
  end
end